//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TypeCobol.LanguageServer.Robot.Monitor.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TypeCobol.LanguageServer.Robot.Monitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Script document is ill-formed..
        /// </summary>
        public static string BadDocumentScript {
            get {
                return ResourceManager.GetString("BadDocumentScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à @ECHO OFF
        ///SET TEST_NAME={0}
        ///SET PATH_TEST=%~dp0
        ///REM {1} = LSR Path value
        ///SET LSR_EXE={1}\LanguageServerRobot.exe
        ///REM {2} = ServerPath value
        ///SET LSP_EXE={2}\TypeCobol.LanguageServer.exe
        ///DEL %PATH_TEST%\Results\%TEST_NAME%.rlsp 2&gt; nul
        ///
        ///SET result=KO
        ///%LSR_EXE% -c -s %LSP_EXE% -script %PATH_TEST%\%TEST_NAME%.tlsp 1&gt; nul 2&gt; nul
        ///FC %PATH_TEST%\%TEST_NAME%.rlsp %PATH_TEST%\Results\%TEST_NAME%.rlsp 1&gt; nul 2&gt; nul
        ///if %ERRORLEVEL%==0 set result=OK
        ///echo %PATH_TEST%\%TEST_NAME%.tlsp %result%
        ///exit %ERRORLEV [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string DefaultBatchTemplate {
            get {
                return ResourceManager.GetString("DefaultBatchTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C:\TypeCobol\Sources\##Latest_Release##.
        /// </summary>
        public static string DefaultLSRPath {
            get {
                return ResourceManager.GetString("DefaultLSRPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C:\TypeCobol\Sources\Sessions.
        /// </summary>
        public static string DefaultScriptRepositoryPath {
            get {
                return ResourceManager.GetString("DefaultScriptRepositoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à C:\TypeCobol\Sources\##Latest_Release##.
        /// </summary>
        public static string DefaultServerPath {
            get {
                return ResourceManager.GetString("DefaultServerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data name field cannot be empty!.
        /// </summary>
        public static string EmptyDataName {
            get {
                return ResourceManager.GetString("EmptyDataName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fail to initialize a scenario recording with TypeCobol LanguageServer..
        /// </summary>
        public static string FailInitalizeScerarioRecording {
            get {
                return ResourceManager.GetString("FailInitalizeScerarioRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to establish a connection message with connection : &apos;{0}&apos;.
        /// </summary>
        public static string FailMessageConnectionWithLSR {
            get {
                return ResourceManager.GetString("FailMessageConnectionWithLSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to stop the scenario recording..
        /// </summary>
        public static string FailStopScenarioRecording {
            get {
                return ResourceManager.GetString("FailStopScenarioRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fail to create a snapshot..
        /// </summary>
        public static string FailToCreateSnapshot {
            get {
                return ResourceManager.GetString("FailToCreateSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fail to get a result from the execution of the scenario : {0}.
        /// </summary>
        public static string FailToGetResultFromScenario {
            get {
                return ResourceManager.GetString("FailToGetResultFromScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fail to read the script file &apos;{0}&apos;.
        /// </summary>
        public static string FailToReadScriptFile {
            get {
                return ResourceManager.GetString("FailToReadScriptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fail to record the snapshot sequence with the server!.
        /// </summary>
        public static string FailToRecordTheSnapshotSequence {
            get {
                return ResourceManager.GetString("FailToRecordTheSnapshotSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fail to replay scenario: {0}.
        /// </summary>
        public static string FailToReplayAScenario {
            get {
                return ResourceManager.GetString("FailToReplayAScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fail to run the LSR process with the following command line: {0} {1}.
        /// </summary>
        public static string FailToRunLSRProcess {
            get {
                return ResourceManager.GetString("FailToRunLSRProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fail to run the LSR process with the following command line: {0} {1} : {2}.
        /// </summary>
        public static string FailToRunLSRProcessExc {
            get {
                return ResourceManager.GetString("FailToRunLSRProcessExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to save data &apos;{0}&apos; &apos;{1}&apos;.
        /// </summary>
        public static string FailToSaveData {
            get {
                return ResourceManager.GetString("FailToSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fail to save the scenario : {0}.
        /// </summary>
        public static string FailToSaveTheScenario {
            get {
                return ResourceManager.GetString("FailToSaveTheScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fail to save the scenario  {0} : {1}.
        /// </summary>
        public static string FailToSaveTheScenarioExc {
            get {
                return ResourceManager.GetString("FailToSaveTheScenarioExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fail to start a connection with the server..
        /// </summary>
        public static string FailToStartServerConnection {
            get {
                return ResourceManager.GetString("FailToStartServerConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid Language Server Robot application path: {0}.
        /// </summary>
        public static string InvalidLSRPath {
            get {
                return ResourceManager.GetString("InvalidLSRPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid Script Repository Path directory: {0}.
        /// </summary>
        public static string InvalidScriptRepositoryPath {
            get {
                return ResourceManager.GetString("InvalidScriptRepositoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid Server Path directory : {0}.
        /// </summary>
        public static string InvalidServerPath {
            get {
                return ResourceManager.GetString("InvalidServerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Language Server Robot application has been interrupted..
        /// </summary>
        public static string LSRConnectioinSideStopped {
            get {
                return ResourceManager.GetString("LSRConnectioinSideStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language Server Robot Monitor.
        /// </summary>
        public static string LSRMName {
            get {
                return ResourceManager.GetString("LSRMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Connection with Language Server Robot.
        /// </summary>
        public static string NoLSRConnection {
            get {
                return ResourceManager.GetString("NoLSRConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recording....
        /// </summary>
        public static string RecordingMessage {
            get {
                return ResourceManager.GetString("RecordingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scenario.
        /// </summary>
        public static string ScenarioCategory {
            get {
                return ResourceManager.GetString("ScenarioCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scenario Editing.
        /// </summary>
        public static string ScenarioEditingTitle {
            get {
                return ResourceManager.GetString("ScenarioEditingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version {0}.
        /// </summary>
        public static string VersionTitle {
            get {
                return ResourceManager.GetString("VersionTitle", resourceCulture);
            }
        }
    }
}
