//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageServer.Robot.Monitor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanguageServer.Robot.Monitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Script document is ill-formed..
        /// </summary>
        public static string BadDocumentScript {
            get {
                return ResourceManager.GetString("BadDocumentScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data name field cannot be empty!.
        /// </summary>
        public static string EmptyDataName {
            get {
                return ResourceManager.GetString("EmptyDataName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to initialize a scenario recording with TypeCobol LanguageServer..
        /// </summary>
        public static string FailInitalizeScerarioRecording {
            get {
                return ResourceManager.GetString("FailInitalizeScerarioRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to establish a connection message with connection : &apos;{0}&apos;.
        /// </summary>
        public static string FailMessageConnectionWithLSR {
            get {
                return ResourceManager.GetString("FailMessageConnectionWithLSR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop the scenario recording..
        /// </summary>
        public static string FailStopScenarioRecording {
            get {
                return ResourceManager.GetString("FailStopScenarioRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save data &apos;{0}&apos; &apos;{1}&apos;.
        /// </summary>
        public static string FailToSaveData {
            get {
                return ResourceManager.GetString("FailToSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Server Robot Monitor.
        /// </summary>
        public static string LSRMName {
            get {
                return ResourceManager.GetString("LSRMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording....
        /// </summary>
        public static string RecordingMessage {
            get {
                return ResourceManager.GetString("RecordingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario.
        /// </summary>
        public static string ScenarioCategory {
            get {
                return ResourceManager.GetString("ScenarioCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario Editing.
        /// </summary>
        public static string ScenarioEditingTitle {
            get {
                return ResourceManager.GetString("ScenarioEditingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string VersionTitle {
            get {
                return ResourceManager.GetString("VersionTitle", resourceCulture);
            }
        }
    }
}
