//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageServerRobot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanguageServerRobot.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A document with the same uri is already opened: {0}.
        /// </summary>
        internal static string DuplicateDidOpenNotification {
            get {
                return ResourceManager.GetString("DuplicateDidOpenNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to create the session directory &apos;{0}&apos;, using default directory &apos;{1}&apos;.
        /// </summary>
        internal static string FailCreateSessionDirectoryUseDefaultPath {
            get {
                return ResourceManager.GetString("FailCreateSessionDirectoryUseDefaultPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to create the session directory : {0}.
        /// </summary>
        internal static string FailtoCreateSessionDirectory {
            get {
                return ResourceManager.GetString("FailtoCreateSessionDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to save script &apos;{0}&apos; : &apos;{1}&apos;.
        /// </summary>
        internal static string FailToSaveScript {
            get {
                return ResourceManager.GetString("FailToSaveScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save script &apos;{0}&apos; there is no session directory..
        /// </summary>
        internal static string FailToSaveScriptNoSessionDirectory {
            get {
                return ResourceManager.GetString("FailToSaveScriptNoSessionDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to session script &apos;{0}&apos; : &apos;{1}&apos;.
        /// </summary>
        internal static string FailToSaveSession {
            get {
                return ResourceManager.GetString("FailToSaveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to save the session there is no directory associated to it..
        /// </summary>
        internal static string FailToSaveSessionNoDirectory {
            get {
                return ResourceManager.GetString("FailToSaveSessionNoDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no session or script for to replay..
        /// </summary>
        internal static string NoSessionOrScriptFile {
            get {
                return ResourceManager.GetString("NoSessionOrScriptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Unexpected Request has been sent from the server: {0}.
        /// </summary>
        internal static string UnexpectedRequestFromServer {
            get {
                return ResourceManager.GetString("UnexpectedRequestFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Unexpected Response has been received from the client: {0}.
        /// </summary>
        internal static string UnexpectedResponseFromClient {
            get {
                return ResourceManager.GetString("UnexpectedResponseFromClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Unexpected Response has been received from the server without a corresponding request: {0}.
        /// </summary>
        internal static string UnexpectedResponseFromServer {
            get {
                return ResourceManager.GetString("UnexpectedResponseFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No &quot;did/Open&quot; notification that matches the &quot;did/Close&quot; notification: {0}.
        /// </summary>
        internal static string UnmatcheDidCloseNotification {
            get {
                return ResourceManager.GetString("UnmatcheDidCloseNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given uri is not associated to a script: {0}.
        /// </summary>
        internal static string UriNotAssociatedToAScript {
            get {
                return ResourceManager.GetString("UriNotAssociatedToAScript", resourceCulture);
            }
        }
    }
}
